COPY locations FROM STDIN WITH CSV HEADER DELIMITER ',' QUOTE '\' NULL AS 'null';
COPY weather_conditions FROM STDIN WITH CSV HEADER DELIMITER ',' QUOTE '\' NULL AS 'null';
COPY astronomical_data FROM STDIN WITH CSV HEADER DELIMITER ',' QUOTE '\' NULL AS 'null';
COPY air_quality FROM STDIN WITH CSV HEADER DELIMITER ',' QUOTE '\' NULL AS 'null';